### PR TITLE
✨ Added cmd.teleport.success for config

### PR DESCRIPTION
**Pull request by FlorianWip**

### CODE REVIEW

**Comment by cokejoke** [comment]
"You were teleported to the Map §a%s§7." klingt nicht so legga.

Mein Vorschlag:
"You've been teleported to the Map §a%s§7."

**Comment by DasLinkeTwiix** [comment]
> "You were teleported to the Map §a%s§7." klingt nicht so legga.
> 
> Mein Vorschlag: "You've been teleported to the Map §a%s§7."

War übrigens mein Vorschlag, nicht der von Justin!!!

**Comment by DasLinkeTwiix** [comment]
> "You were teleported to the Map §a%s§7." klingt nicht so legga.
> 
> Mein Vorschlag: "You've been teleported to the Map §a%s§7."

War mein Vorschlag, nicht von Justin!!!

**Review by cokejoke — APPROVED** [review]
👌

**Pull request merged**
